spring:
  rabbitmq:
    host: 10.214.242.155 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /vipaCompression # 虚拟主机
    username: vipaCompression # 用户名
    password: vipa@404 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mc_client155_1
#    ?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    username: lhl
    password: 2000114lhl  # 这个是服务器上的
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8384
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: org.zjuvipa.compression.model.entity

logging:
  level:
    org.zjuvipa.mapper: debug

