spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modelcompression
#    ?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    username: lhl
    password: 2000114lhl  # 这个是服务器上的
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  # Redis的相关配置
  redis:
    host: localhost
    port: 6380
server:
  port: 7996
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: org.zjuvipa.compression.model.entity

logging:
  level:
    org.zjuvipa.mapper: debug

modelcompression:
  auth:
    noAuthUrls:
      - /user/login
      - /user/captcha
      - /user/register
  minio:
    endpointUrl: http://10.214.242.155:9000
    accessKey: minioadmin
    secreKey: minioadmin
    bucketName: modelcompression-bucket

